### ISSUE TITLE
CRASH in ^L LIST (v0.0.14)

### ISSUE THREAD

**Issue by Monk-Data** [golbin/git-commander#43]
Can be replicated (currently) with a clone of https://github.com/ramda/ramda
-- CHRIS

$ pwd
/home/cms/source/ramda
$ ls
BOOKMARKLET.md  CHANGELOG.md     dist  LICENSE.txt  package.json  scripts  test
bower.json      CONTRIBUTING.md  lib   Makefile     README.md     src      testem.json
$ git-commander

   .. then press CTRL-L ...

TypeError: Cannot read property 'slice' of null
    at /home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/program.js:2543:35
    at Array.forEach (native)
    at Program._attr (/home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/program.js:2542:11)
    at Box.Element._parseTags (/home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/element.js:498:26)
    at Box.Element.parseContent (/home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/element.js:393:22)
    at Box.<anonymous> (/home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/element.js:184:10)
    at Box.EventEmitter._emit (/home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/events.js:94:20)
    at Box.EventEmitter.emit (/home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/events.js:117:12)
    at emit (/home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/node.js:109:15)
    at ScrollableBox.Node.insert (/home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/node.js:111:5)

$ cd /home/cms/.nvm/versions/node/v0.12.7/lib/node_modules/git-commander/

$ cat package.json
{
  "name": "git-commander",
  "version": "0.0.14",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/golbin/git-commander.git"
  },
  "homepage": "https://github.com/golbin/git-commander",
  "bugs": {
    "url": "https://github.com/golbin/git-commander/issues"
  },
  "dependencies": {
    "blessed": "^0.1.7",
    "lodash": "^3"
  },
  "devDependencies": {},
  "engines": {
    "node": "^0.12"
  },
  "main": "controller/main.js",
  "bin": {
    "git-commander": "./bin/git-commander"
  },
  "keywords": [
    "git",
    "terminal"
  ],
  "directories": {
    "doc": "doc"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "gitHead": "7962bb4d22f26e2459aea8c8a640b1226fa60e90",
  "description": "A git tool with an easy terminal interface.",
  "_id": "git-commander@0.0.14",
  "_shasum": "9c0c4fca2fa2594e394f5cee0834af78b7c68ccd",
  "_from": "git-commander@*",
  "_npmVersion": "2.13.4",
  "_nodeVersion": "0.12.7",
  "_npmUser": {
    "name": "golbin",
    "email": "golbin@gmail.com"
  },
  "maintainers": [
    {
      "name": "golbin",
      "email": "golbin@gmail.com"
    }
  ],
  "dist": {
    "shasum": "9c0c4fca2fa2594e394f5cee0834af78b7c68ccd",
    "tarball": "http://registry.npmjs.org/git-commander/-/git-commander-0.0.14.tgz"
  },
  "_resolved": "https://registry.npmjs.org/git-commander/-/git-commander-0.0.14.tgz"
}

**Comment by vbauer** [comment]
I have the same problem:
```
TypeError: Cannot read property 'slice' of null
    at /usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/program.js:2543:35
    at Array.forEach (<anonymous>)
    at Program._attr (/usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/program.js:2542:11)
    at Box.Element._parseTags (/usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/element.js:498:26)
    at Box.Element.parseContent (/usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/element.js:393:22)
    at Box.<anonymous> (/usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/element.js:184:10)
    at Box.EventEmitter._emit (/usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/events.js:94:20)
    at Box.EventEmitter.emit (/usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/events.js:117:12)
    at emit (/usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/node.js:109:15)
    at List.Node.insert (/usr/local/lib/node_modules/git-commander/node_modules/blessed/lib/widgets/node.js:111:5)
```
